title: "Meenu Krishnan"
author: U. Meenu Krishnan
email: ukrishn4@jh.edu

url: "https://www.krishnanmeenu.com"

description: >
  Postdoctoral Research Fellow at Johns Hopkins University.
  Researcher in Computational Mechanics, Machine Learning, and Structural Optimization.

favicon: "/favicon.ico"
avatar: "/assets/images/meenu.png"

permalink: /:year/:month/:day/:title/
show_excerpts: true

social:
  scholar: hjyZvdgAAAAJ
  github: umeenukrishnan
  researchgate: Meenu_Krishnan
  linkedin: iitrmeenu
  instagram: univ_tusk_mind
  youtube: channel/UCzFrF4BI7298HWKzcXCciAg

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .DS_Store
  - "*.sublime-workspace"
  - "*.sublime-project"
  - README.md
  - _plugins
